kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Configurazione della rete del cluster simulato
networking:
  disableDefaultCNI: false # Usa la rete standard bridge

# Definizione dei Nodi (I nostri Satelliti)
nodes:
  # --- SATELLITE 0: Control Plane (Il Comandante) ---
  - role: control-plane
    image: kindest/node:v1.30.0  # Versione K8s recente per supporto Checkpoint
    kubeadmConfigPatches:
    # ABILITAZIONE CHECKPOINTING: Permette di estrarre lo stato della RAM dei container tramite API e SIMULAZIONE ACCELERATA
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true 
        nodeStatusUpdateFrequency: "2s"
    # Se un nodo non risponde per 10s, è considerato "disperso" nello spazio
      - |
        kind: ClusterConfiguration
        controllerManager:
          extraArgs:
            node-monitor-grace-period: "10s"

  # --- SATELLITE 1: Worker (Operativo) ---
  - role: worker
    image: kindest/node:v1.30.0
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true
        nodeStatusUpdateFrequency: "2s"

  # --- SATELLITE 2: Worker (Operativo) ---
  - role: worker
    image: kindest/node:v1.30.0
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true
        nodeStatusUpdateFrequency: "2s"