kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Configurazione della rete
networking:
  disableDefaultCNI: false 

# Definizione dei Nodi (I nostri Satelliti)
nodes:
  # --- SATELLITE 0: Control Plane (Il Comandante + INGRESS PORT) ---
  - role: control-plane
    image: kindest/node:v1.30.0
    
    # 1. MAPPATURA PORTE (NOVITÀ PER INGRESS)
    # Apriamo le porte verso il tuo PC
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
    
    kubeadmConfigPatches:
      # 2. LABEL INGRESS (NOVITÀ)
      # Dice a NGINX di installarsi qui dove ci sono le porte aperte
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"

      # 3. ABILITAZIONE CHECKPOINTING (VECCHIA LOGICA)
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true 
        nodeStatusUpdateFrequency: "2s"
      
      # 4. MONITORAGGIO VELOCE (VECCHIA LOGICA)
      - |
        kind: ClusterConfiguration
        controllerManager:
          extraArgs:
            node-monitor-grace-period: "10s"

  # --- SATELLITE 1: Worker (Operativo) ---
  - role: worker
    image: kindest/node:v1.30.0
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true
        nodeStatusUpdateFrequency: "2s"

  # --- SATELLITE 2: Worker (Operativo) ---
  - role: worker
    image: kindest/node:v1.30.0
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true
        nodeStatusUpdateFrequency: "2s"