kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Configurazione della rete
networking:
  disableDefaultCNI: false 

nodes:
  # --- SATELLITE 0: Control Plane ---
  - role: control-plane
    image: space-cloud-node-criu:v1
    # Mappatura per Ingress (Traffico Web)
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP

    # === PONTE DATI (CRUCIALE PER CHECKPOINT) ===
    # Mappa la cartella dei checkpoint del nodo su una cartella del tuo PC
    extraMounts:
    - hostPath: /tmp/space-checkpoints   # Sul tuo PC
      containerPath: /var/lib/kubelet/checkpoints # Sul Nodo (Standard K8s)

    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      # Abilitiamo Feature Gate (anche se in 1.30 è Beta, meglio essere espliciti)
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true 
        nodeStatusUpdateFrequency: "2s"

  # --- SATELLITE 1: Worker ---
  - role: worker
    image: space-cloud-node-criu:v1
    # Anche i worker devono poter salvare i checkpoint sul tuo PC
    extraMounts:
    - hostPath: /tmp/space-checkpoints
      containerPath: /var/lib/kubelet/checkpoints

    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true
        nodeStatusUpdateFrequency: "2s"

  # --- SATELLITE 2: Worker ---
  - role: worker
    image: space-cloud-node-criu:v1
    extraMounts:
    - hostPath: /tmp/space-checkpoints
      containerPath: /var/lib/kubelet/checkpoints

    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        featureGates:
          ContainerCheckpoint: true
        nodeStatusUpdateFrequency: "2s"