# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import checkpoint_transfer_pb2 as checkpoint__transfer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in checkpoint_transfer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileTransferStub(object):
    """=================================================================
    1. IL SERVIZIO (Il "Lavoro" che il nodo sa fare)
    =================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCheckpoint = channel.stream_unary(
                '/spacecloud.FileTransfer/StreamCheckpoint',
                request_serializer=checkpoint__transfer__pb2.Chunk.SerializeToString,
                response_deserializer=checkpoint__transfer__pb2.TransferStatus.FromString,
                _registered_method=True)


class FileTransferServicer(object):
    """=================================================================
    1. IL SERVIZIO (Il "Lavoro" che il nodo sa fare)
    =================================================================
    """

    def StreamCheckpoint(self, request_iterator, context):
        """Metodo StreamCheckpoint:
        - Riceve: "stream Chunk" (Un flusso continuo di pezzettini di file)
        - Restituisce: "TransferStatus" (Una ricevuta singola alla fine)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCheckpoint': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamCheckpoint,
                    request_deserializer=checkpoint__transfer__pb2.Chunk.FromString,
                    response_serializer=checkpoint__transfer__pb2.TransferStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spacecloud.FileTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spacecloud.FileTransfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileTransfer(object):
    """=================================================================
    1. IL SERVIZIO (Il "Lavoro" che il nodo sa fare)
    =================================================================
    """

    @staticmethod
    def StreamCheckpoint(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/spacecloud.FileTransfer/StreamCheckpoint',
            checkpoint__transfer__pb2.Chunk.SerializeToString,
            checkpoint__transfer__pb2.TransferStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
