# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: checkpoint_transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'checkpoint_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63heckpoint_transfer.proto\x12\nspacecloud\"\x18\n\x05\x43hunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"2\n\x0eTransferStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\x0c\x46ileTransfer\x12\x45\n\x10StreamCheckpoint\x12\x11.spacecloud.Chunk\x1a\x1a.spacecloud.TransferStatus\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkpoint_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNK']._serialized_start=41
  _globals['_CHUNK']._serialized_end=65
  _globals['_TRANSFERSTATUS']._serialized_start=67
  _globals['_TRANSFERSTATUS']._serialized_end=117
  _globals['_FILETRANSFER']._serialized_start=119
  _globals['_FILETRANSFER']._serialized_end=204
# @@protoc_insertion_point(module_scope)
