apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-ingress
  annotations:
    # Opzionale: riscrive l'URL se necessario (qui non serve, ma è utile saperlo)
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # FONDAMENTALE: Dice a K8s di usare il controller che abbiamo installato in Fase 2
  ingressClassName: nginx
  rules:
  - host: mission-control.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: space-mission-service # Deve coincidere con il nome del Service
            port:
              number: 80 # La porta del Service (non del Pod!)