apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-ingress
  annotations:
    # Rewrite target non necessario se l'app risponde su /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: space-mission-service # Deve matchare il nome nel space-mission.yaml
            port:
              number: 80