apiVersion: v1
kind: Service
metadata:
  name: system-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: system-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-redis
  template:
    metadata:
      labels:
        app: system-redis
    spec:
      # === VINCOLO DI TERRA ===
      # Questo pod girerà SOLO sul nodo etichettato come ground-station (minikube)
      nodeSelector:
        type: ground-station
      containers:
        - name: redis
          image: docker.io/library/redis:alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"