import time
import json
import redis
import logging
import os

# =============================================================================
#  SPACE CLOUD V5.2 - MPC CONTROLLER (Event-Driven Brain)
#  Role: Listens to sensors via Pub/Sub and transmits migration orders via Redis.
# =============================================================================

# --- Safety Thresholds ---
CRITICAL_BATTERY = 30.0    # Minimum battery level before triggering migration
CRITICAL_TEMP_HIGH = 80.0  # Safe thermal limit; migration starts if predicted to exceed this
FUSION_TEMP = 120.0       # Hardware destruction limit; triggers emergency shutdown
PREDICTION_HORIZON = 60    # Look-ahead window in seconds for the predictive engine
MIGRATION_COOLDOWN = 30    # Seconds to wait after landing before allowing new risks/migrations

# --- Physical Constants for Orbital Simulation ---
ORBIT_PERIOD = 120.0       # Time for a full 360° orbit
ECLIPSE_START = 220        # Orbital angle where the satellite enters the Earth's shadow
ECLIPSE_END = 320          # Orbital angle where the satellite exits the shadow
HEATING_SUN = 100.0        # Thermal input from solar radiation
HEATING_CPU_LOAD = 85.0    # Thermal input generated by the AI workload (Phoenix)
COOLING_K = 4.0            # Radiation cooling constant
THERMAL_MASS = 40.0        # Resistance to temperature change
BATTERY_CHARGE_RATE = 5.0  # Power gain when in sunlight
BATTERY_DRAIN_LOAD = 2.5   # Continuous power drain from the AI workload

# Configure logging for real-time monitoring
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [MPC] %(message)s', datefmt='%H:%M:%S')
logger = logging.getLogger("MPC")


def connect_redis():
    """Attempts to establish a connection with the central Redis Message Broker."""
    try:
        r = redis.Redis(host='localhost', port=6379, decode_responses=True, socket_connect_timeout=2)
        r.ping() # Verify connection is alive
        return r
    except:
        return None


# --- PREDICTIVE ENGINE ---
class VirtualSatellite:
    """Mathematical model used to simulate the satellite's future state."""
    def __init__(self, data_dict):
        # Initialize the virtual model with the current real-world telemetry
        self.battery = float(data_dict.get('battery', 100))
        self.temp = float(data_dict.get('temp', 20))
        self.angle = float(data_dict.get('angle', 0))

    def predict_future(self, seconds):
        """Integrates physical laws forward in time to spot risks before they happen."""
        dt = 1.0 # 1-second simulation step
        steps = int(seconds / dt)
        deg_per_sec = 360.0 / ORBIT_PERIOD

        for _ in range(steps):
            # Update orbital position
            self.angle = (self.angle + deg_per_sec) % 360.0
            in_eclipse = (ECLIPSE_START <= self.angle <= ECLIPSE_END)

            # Thermal Power Balance: P_in (CPU + Sun) - P_out (Radiation)
            p_in = HEATING_CPU_LOAD
            if not in_eclipse: p_in += HEATING_SUN
            # Simplified Stefan-Boltzmann cooling relative to deep space (-270°C)
            p_out = COOLING_K * (self.temp - (-270)) * 0.1
            self.temp += (p_in - p_out) / THERMAL_MASS * dt

            # Energy Balance: Charge (Sun) - Discharge (Load)
            charge = BATTERY_CHARGE_RATE if not in_eclipse else 0.0
            self.battery += (charge - BATTERY_DRAIN_LOAD) * dt
            self.battery = max(0.0, min(100.0, self.battery))

            # Threshold Violation Check
            if self.battery < CRITICAL_BATTERY:
                return False, f"LOW BATTERY PREDICTION (<{CRITICAL_BATTERY}%)"
            if self.temp > CRITICAL_TEMP_HIGH:
                return False, f"THERMAL RUNAWAY PREDICTION (>{CRITICAL_TEMP_HIGH}°C)"

        return True, "SAFE"


# --- CONTROL LOGIC ---
def find_best_target(fleet_state, current_node):
    """Cost-function to select the optimal satellite for migration."""
    best_node = None
    best_score = -9999

    for name, data in fleet_state.items():
        if name == current_node: continue      # Don't migrate to the same node
        if data['type'] == 'ground': continue # Workload must stay on satellites

        # Heuristic: Favor high battery, lower temperature, and sunlight exposure
        score = data['battery'] * 2
        score -= data['temp']
        if not data['eclipse']: score += 50 # Massive bonus for being in the sun

        if score > best_score:
            best_score = score
            best_node = name

    return best_node


def trigger_migration(redis_client, source, dest):
    """Publishes a migration command to the specific node channel in Redis."""
    logger.warning(f"🚨 ACTION: MIGRATION ORDER {source} -> {dest}")
    payload = {"action": "MIGRATE", "target_node": dest}
    channel = f"commands/{source}"
    try:
        redis_client.publish(channel, json.dumps(payload))
        logger.info(f"✅ Order successfully transmitted on channel '{channel}'.")
    except Exception as e:
        logger.error(f"❌ Failed to transmit order: {e}")


def watchdog(current_temp):
    """Emergency system that kills the workload if hardware failure (fusion) is imminent."""
    if current_temp > FUSION_TEMP:
        logger.critical(f"🔥 IMMINENT MELTDOWN ({current_temp}°C). EMERGENCY KILL.")
        # Forceful deletion of the Kubernetes deployment to save the virtual hardware
        os.system("kubectl delete deployment space-mission > /dev/null 2>&1")
        return True
    return False


# =============================================================================
# THE BRAIN (Main Event Loop)
# =============================================================================
def main():
    logger.info("🧠 MPC BRAIN V5.2 ONLINE. Waiting for Sensor Link (Pub/Sub)...")

    # Local mirror of the fleet state updated by telemetry
    fleet_state = {}

    # State Machine Variables
    last_migration_time = 0
    migrating_to = None      # Stores the target node during transit
    migration_start_time = 0
    MIGRATION_TIMEOUT = 120  # Reset transit state if landing is not confirmed in 2 mins

    system_start_time = time.time()
    BOOT_GRACE_PERIOD = 20   # Ignore risks during first 20s of system boot

    while True:
        r = connect_redis()
        if not r:
            time.sleep(1)
            continue

        try:
            pubsub = r.pubsub()
            # Subscribe to all telemetry channels using a pattern
            pubsub.psubscribe('telemetry/*')
            logger.info("📡 Link established. Subscribed to telemetry/*")

            for message in pubsub.listen():
                if message['type'] == 'pmessage':
                    # Parse telemetry data
                    channel = message['channel']
                    node_name = channel.split('/')[1]
                    node_data = json.loads(message['data'])
                    fleet_state[node_name] = node_data

                    # Identify which node is currently hosting the workload
                    active_node = None
                    for name, data in fleet_state.items():
                        if data.get('is_working', False):
                            active_node = name
                            break

                    # -----------------------------------------------------------------
                    # 1. STATE MANAGEMENT: "IN TRANSIT"
                    # -----------------------------------------------------------------
                    if migrating_to:
                        # Check if the workload has successfully surfaced on the target node
                        if active_node == migrating_to:
                            logger.info(
                                f"🛬 LANDING CONFIRMED on {active_node}! Starting safety Cooldown ({MIGRATION_COOLDOWN}s).")
                            migrating_to = None
                            last_migration_time = time.time() # Stabilization cooldown starts now

                        # Handle migration failure/lost pod
                        elif time.time() - migration_start_time > MIGRATION_TIMEOUT:
                            logger.error(f"❌ TIMEOUT: {migrating_to} lost in space. Resetting sensors.")
                            migrating_to = None
                            last_migration_time = time.time()

                        else:
                            # Periodic logging during the gRPC transfer/K8s rescheduling phase
                            if node_name == migrating_to and int(time.time()) % 2 == 0:
                                logger.info(f"🚀 IN TRANSIT... Waiting for telemetry from the new pod on {migrating_to}...")

                        continue # Ignore all other rules while a migration is in progress

                    # Wait if no pod is active and we are not migrating
                    if not active_node: continue

                    # -----------------------------------------------------------------
                    # 2. STATE MANAGEMENT: "OPERATIONAL" (Risk Monitoring)
                    # -----------------------------------------------------------------
                    if node_name == active_node:
                        current_data = fleet_state[active_node]

                        # Immediate hardware protection
                        if watchdog(current_data['temp']): continue

                        # Run the Predictive Engine for the next 60 seconds
                        sim = VirtualSatellite(current_data)
                        is_safe, reason = sim.predict_future(PREDICTION_HORIZON)

                        if not is_safe:
                            # Skip migration if we are still in the initial boot phase
                            time_since_boot = time.time() - system_start_time
                            if time_since_boot < BOOT_GRACE_PERIOD:
                                if int(time.time()) % 5 == 0:
                                    logger.info(
                                        f"⏳ Boot Sequence: Ignoring risk '{reason}' for another {int(BOOT_GRACE_PERIOD - time_since_boot)}s")
                                continue

                            # Skip migration if we just landed (stabilization period)
                            time_since = time.time() - last_migration_time
                            if time_since < MIGRATION_COOLDOWN:
                                logger.info(
                                    f"⚠️  Risk: {reason} (Stabilization cooldown: {int(MIGRATION_COOLDOWN - time_since)}s)")
                            else:
                                # PREDICTION ALERT: Initiate migration procedure
                                logger.warning(f"🔮 PREDICTION ON NODE {active_node}: {reason}")
                                target = find_best_target(fleet_state, active_node)
                                if target:
                                    trigger_migration(r, active_node, target)
                                    # Update State Machine to Transit Mode
                                    migrating_to = target
                                    migration_start_time = time.time()
                                else:
                                    logger.error("😱 NO SAFE TARGETS! BRACE FOR IMPACT.")
                        else:
                            # Routine status log
                            if int(time.time()) % 10 == 0:
                                logger.info(f"✅ Node {active_node} Operational. Prediction: SAFE.")

        except redis.ConnectionError:
            logger.error("❌ Redis connection lost. Reconnecting in 2s...")
            time.sleep(2)
        except Exception as e:
            logger.error(f"Event Loop Error: {e}")
            time.sleep(1)


if __name__ == "__main__":
    main()