apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: space-mission-service  # Assicurati che il tuo Service si chiami così!
            port:
              number: 80